---
server:
  url: "http://localhost:3001"

setup:
  type: mariadb
  hostname: db
  username: kuma
  password: kuma
  dbName: kuma

auth:
  username: root
  password: testtest0

notifications:
  - name: kalexlab
    type: telegram
    telegramBotToken: "1234"
    telegramChatID: "1234"

monitors:
  - type: http
    name: http test
    url: "https://google.com"
    interval: 60
    authMethod: basic
    basic_auth_user: test
    basic_auth_pass: test
    notifications:
      - kalexlab
  - type: ping
    name: ping test
    hostname: www.google.com

status_pages:
  - title: test
    slug: test-slug
    description: test description
    groups:
      - name: "group 1"
        monitors:
          - test
